name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            platform: linux
          - os: windows-latest
            platform: windows
          - os: macos-latest
            platform: macos

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Set up CMake
      shell: bash
      run: |
        cmake --version
        if [ "${{ matrix.platform }}" = "linux" ]; then
          sudo apt-get update
          sudo apt-get install -y ninja-build libgtk-3-dev
        fi

    - name: Configure CMake
      shell: bash
      run: |
        mkdir build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release

    - name: Build Examples
      shell: bash
      run: |
        cd build
        cmake --build . --config Release

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: examples-${{ matrix.platform }}
        path: build/examples/screen_info/ 